image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
  - hut
  - nim
  - nimble
  - pcre
tasks:
  - test: |
      cd matext
      nimble test -y
  - upload: |
      if test "$(git -C matext rev-parse HEAD)" = "$(git -C matext rev-parse master)"; then
        tar -cvzC matext/site . -f site.tar.gz
        hut pages publish -d xigoi.srht.site -s matext site.tar.gz
      fi
